SET NOCOUNT ON

/* Only Add initial data once */
IF (SELECT COUNT(*) FROM Users WHERE userId=1) = 0 BEGIN

	/* Setup Variable */
	DECLARE 
	@websiteId int = 0,
	@websiteTitle nvarchar(100) = 'Websilk',
	@pageDescription nvarchar(MAX) = 'Welcome to your new website, generated by the Websilk platform.'

	/* Create Default Administration Account */
	EXEC User_Create @email='admin@localhost', @password='', @displayname='admin', @photo='', @status=1

	/* Create Default Website */
	EXEC @websiteId = Website_Create @ownerId=1, @title=@websiteTitle, @description=@pageDescription, 
					@status=1, @logo='', @security=0, @enabled=1, @liveurl='www.websilk.io', @stageurl='new.websilk.io'
	
END