CREATE TABLE [dbo].[LogAnalytics] (
    [websiteId]       INT            NOT NULL,
    [pageId]          INT            NULL,
    [countryCode]     NVARCHAR (3)   NULL,
    [agent]           NVARCHAR (200) NULL,
    [referrer]        NVARCHAR (200) NULL,
    [logYear]         SMALLINT       NULL,
    [logMonth]        SMALLINT       NULL,
    [logDay]          SMALLINT       NULL,
    [dateModified]    DATETIME       NULL,
    [totalViews]      INT            NULL,
    [totalBots]       INT            NULL,
    [totalLoadTime]   FLOAT (53)     NULL,
    [avgLoadTime]     FLOAT (53)     NULL,
    [totalAjax]       INT            NULL,
    [totalVisitors]   INT            NULL,
    [maxVisitorViews] INT            NULL,
    [avgVisitorViews] FLOAT (53)     NULL,
    [totalUsers]    INT            NULL,
    [maxUserViews]  INT            NULL,
    [avgUserViews]  FLOAT (53)     NULL,
    [bounceRate]      FLOAT (53)     NULL,
    [totalComponents] FLOAT (53)     NULL,
    [avgComponents]   FLOAT (53)     NULL,
    [totalApps]       FLOAT (53)     NULL,
    [avgApps]         FLOAT (53)     NULL,
    [totalInterfaces] FLOAT (53)     NULL,
    [avgInterfaces]   FLOAT (53)     NULL,
    [totalSqlQueries] FLOAT (53)     NULL,
    [avgSqlQueries]   FLOAT (53)     NULL,
    [totalCtext]      FLOAT (53)     NULL,
    [avgCtext]        FLOAT (53)     NULL,
    [totalCphotos]    FLOAT (53)     NULL,
    [avgCphotos]      FLOAT (53)     NULL,
    [totalCgalleries] FLOAT (53)     NULL,
    [avgCgalleries]   FLOAT (53)     NULL,
    [totalCpanels]    FLOAT (53)     NULL,
    [avgCpanels]      FLOAT (53)     NULL,
    [totalCmenus]     FLOAT (53)     NULL,
    [avgCmenus]       FLOAT (53)     NULL,
    [totalEditor]     INT            NULL,
    [totalDash]       INT            NULL, 
    CONSTRAINT [PK_LogAnalytics] PRIMARY KEY ([websiteId])
);


GO

CREATE INDEX [index_logAnalytics] ON [dbo].[LogAnalytics] (websiteId, logYear DESC, logMonth, logDay)
